/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.fixacceptor;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appLoads() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "App should be instantiated");
    }
}
