/*
 * This source file was generated by the Gradle 'init' task
 */

package com.example.fixacceptor;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import quickfix.Application;
import quickfix.Message;
import quickfix.SessionID;
import quickfix.SessionSettings;
import quickfix.SocketAcceptor;
import quickfix.MessageStoreFactory;
import quickfix.FileStoreFactory;
import quickfix.LogFactory;
import quickfix.FileLogFactory;
import quickfix.DefaultMessageFactory;
import quickfix.ConfigError;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        try {
            // Use resource path relative to working directory
            SessionSettings settings = new SessionSettings("src/main/resources/quickfixj.cfg");
            Application application = new Application() {
                @Override
                public void onCreate(SessionID sessionId) {
                    logger.info("Session created: {}", sessionId);
                }
                @Override
                public void onLogon(SessionID sessionId) {
                    logger.info("Logon: {}", sessionId);
                }
                @Override
                public void onLogout(SessionID sessionId) {
                    logger.info("Logout: {}", sessionId);
                }
                @Override
                public void toAdmin(Message message, SessionID sessionId) {}
                @Override
                public void fromAdmin(Message message, SessionID sessionId) {}
                @Override
                public void toApp(Message message, SessionID sessionId) {}
                @Override
                public void fromApp(Message message, SessionID sessionId) {
                    logger.info("Received app message: {}", message);
                }
            };
            MessageStoreFactory storeFactory = new FileStoreFactory(settings);
            LogFactory logFactory = new FileLogFactory(settings);
            SocketAcceptor acceptor = new SocketAcceptor(
                application,
                storeFactory,
                settings,
                logFactory,
                new DefaultMessageFactory()
            );
            acceptor.start();
            logger.info("FIX Acceptor started. Press Ctrl+C to exit.");
            // Keep running
            while (true) {
                Thread.sleep(1000);
            }
        } catch (ConfigError | InterruptedException e) {
            logger.error("Error starting FIX Acceptor", e);
        }
    }
}
